"use client";

import { createBrowserClient } from '@supabase/ssr';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// This is the client-side Supabase client.
// It's used in client components and can be used for fetching data,
// but it's often better to use Server Actions for data mutations
// to keep sensitive logic on the server.

// HINT: The 'Database' type is generated by the Supabase CLI.
// We'll define a placeholder for it in src/types/supabase.ts for now.

let client: SupabaseClient<Database> | undefined;

function getSupabaseClient() {
  if (client) {
    return client;
  }

  // Ensure environment variables are set
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    throw new Error('Missing Supabase environment variables');
  }

  client = createBrowserClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  );
  
  return client;
}

export const supabase = getSupabaseClient();
