import { createServerClient, type CookieOptions } from '@supabase/ssr'
import { cookies } from 'next/headers'
import type { Database } from '@/types/supabase';

// This is the server-side Supabase client.
// It's used in Server Components, Server Actions, and Route Handlers.
// It has admin-level privileges because it uses the SERVICE_ROLE_KEY.
// Be careful when using this client, as it bypasses Row Level Security.

// HINT: The 'Database' type is generated by the Supabase CLI.
// We'll define a placeholder for it in src/types/supabase.ts for now.

export function createSupabaseServerClient() {
  const cookieStore = cookies()

  // Ensure environment variables are set
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    // In a real app, you'd want more robust error handling or logging.
    // For this example, we'll avoid throwing an error during build/static generation.
    console.error("Supabase server credentials not found. Returning a mock client.");
    // Return a mock client if variables are not set
    return {
        from: () => ({
            select: () => ({
                in: () => ({
                    eq: () => ({
                        eq: () => Promise.resolve({ data: [], error: { message: "Mock client: Env vars not set", details: "", hint: "", code: "" } })
                    })
                })
            })
        })
    };
  }

  return createServerClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
      },
    }
  )
}
