// This file is a placeholder for the types generated by `supabase gen types typescript`.
// In a real project, you would run this command to get full type safety
// with your database schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          phone: string | null
          online: boolean | null
          active_at: string | null
          alias: string | null
          images: string[] | null
          province: string | null
          municipality: string | null
          vehicle_type: "electric" | "combustion" | "hybrid" | null
        }
        Insert: {
          id: string
          phone?: string | null
          online?: boolean | null
          active_at?: string | null
          alias?: string | null
          images?: string[] | null
          province?: string | null
          municipality?: string | null
          vehicle_type?: "electric" | "combustion" | "hybrid" | null
        }
        Update: {
          id?: string
          phone?: string | null
          online?: boolean | null
          active_at?: string | null
          alias?: string | null
          images?: string[] | null
          province?: string | null
          municipality?: string | null
          vehicle_type?: "electric" | "combustion" | "hybrid" | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      vehicle_type_enum: "electric" | "combustion" | "hybrid"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
